### ISSUE TITLE
Email not flagged as read

### ISSUE THREAD

**Issue by marco-trovato** [adbenitez/deltalab-android#10] opened 2022-06-28 10:58 UTC
- Android version: All
- Device: All
- Delta Chat version: 1.30.3

- Expected behavior: After reading an email or selecting BLOCK when receiving one from a new address, the email is supposed to be marked as read.

- Actual behavior: Gmail chaos with thousands of unread email because they all have been opened with DeltaLab.

- Steps to reproduce the problem: Easily reproducible by opening any other email client

Please do not understimate this simple bug, it makes the app unusable because as it is now the user have to open Mozilla Thunderbird or Gmail webmail to manually select as read every single message. It will not be long and people will eventually get bored and uninstall DeltaLab.

**Comment by adbenitez** [comment] 2022-07-15 12:04
hi @marco-trovato, if it is a contact request, messages are not marked as read I guess, but otherwise they should be marked as read, I guess this is an issue with delta chat core, you need to provide more info, logs, and explain better the issue, how to reproduce step by step

**Comment by adbenitez** [comment] 2022-07-15 12:05
in case of reading without accepting the chat and then blocking, I think it is intended they are not marked as read

**Closed** 2022-10-12 19:05 UTC
